print("---------------------------------------")
print("Task 36: Print a number from the user")
number=int(input("Please put a number:"))
print(f"The number you have put is {number}")
print("---------------------------------------")
print("Task 37: Print the sum of two numbers from the user")
number1=int(input("Please put the first number:"))
number2=int(input("Please put the second number:"))
print(f"The sum of your two numbers is {number1+number2}")
print("---------------------------------------")
print("Task 38: Print the mult of two numbers from the user")
number1=int(input("Please put the first number:"))
number2=int(input("Please put the second number:"))
print(f"The mult of your two numbers is {number1*number2}")
print("---------------------------------------")
print("Task 39: Print the power of two numbers from the user")
number1=int(input("Please put the first number:"))
number2=int(input("Please put the second number:"))
print(f"The power of your two numbers is {number1**number2}")
print("---------------------------------------")
print("Task 40: Print a rectangle space from the user")
base=int(input("Please put the base length:"))
height=int(input("Please put the height:"))
print(f"Your rectangle space is: {base*height}")
print("---------------------------------------")
print("Task 41: The average of three numbers from the user")
number1=int(input("Please put the first number:"))
number2=int(input("Please put the second number:"))
number3=int(input("Please put the third number:"))
print(f"The average of the three numbers you have put is: {(number1+number2+number3)/3}")
print("---------------------------------------")
print("Task 43: Write a program that calculates a user age")
yearborn=int(input("Put the year you were born:"))
print(f"Your age is: {2024-yearborn}")
print("---------------------------------------")
print("Task 45: Write a program that calculates a product price after VAT")
beforevat=int(input("Put the price to calculate the VAT:"))
print("The price after VAT is: ",beforevat*1.17)
print("---------------------------------------")
print("Task 46: ")