'''
print("Task 1: Print a program that prints a user age and name")
name=input("Put your name:")
age=int(input("Put your age:"))
print(f"Your name is {name} and your age is {age}")
print("--------------------------------------------------------")
print("Task 2: Print a program that calculates a triangle space")
base=int(input("Put the base length:"))
height=int(input("Put the height length:"))
print(f"The space of the triangle is {base*height/2}")
print("--------------------------------------------------------")
print("Task 3: Create three variables and print their types")
x=10
y="hello"
z=0.13
print(type(x))
print(type(y))
print(type(z))
print("--------------------------------------------------------")
print("Task 4: Do a program that takes two numbers and prints")
numberone=int(input("Put the first number: "))
numbertwo=int(input("Put the second number: "))
print(f"The first number by the power of two is {numberone**2}")
print(f"The first number by the power of the second number is {numberone**numbertwo}")
print(f"The full division of number two by number one is {numbertwo//numberone}")
print("--------------------------------------------------------")
print("Do a program that takes a shirt price and the number of shirts bought")
print("Calculate the full price with VAT and without VAT")
shirtprice=int(input("Put the price of the shirt:"))
shirts=int(input("How many shirts?:"))
print(f"The price with 17% VAT is {shirtprice*shirts*1.17}")
print(f"The price without VAT is {shirtprice*shirts}")
print(f"The price with VAT and with 20% discount is {shirtprice*shirts*1.17*0.80}")
print(f"The price without VAT and with 20% discount is {shirtprice*shirts*0.80}")
print("--------------------------------------------------------")
'''